databases:
  - name: capstone
    databaseName: capstone
    user: capstone

services:
  - type: web
    name: capstone
    env: ruby
    repo: https://github.com/HannahChristmas/capstone
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: capstone
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false