# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts "🏈 Seeding activities..."

activity1 = Activity.create(title: 'Dinner Train', neighborhood: 'Golf Manor', cost: 95, address: '2172 E Seymour Ave, Cincinnati, OH 45237', phone_number: '(513) 791-7245', website: 'https://cincinnatidinnertrain.com/')
activity2 = Activity.create(title: 'Music Hall Tour', neighborhood: 'OTR', cost: 15, address: '1241 Elm St, Cincinnati, OH 45202', phone_number: '(513) 744-3293', website: 'https://friendsofmusichall.org/music-hall-tours/')
activity3 = Activity.create(title: 'Behringer Crawford Museum', neighborhood: 'Covington', cost: 9, address: '1600 Montague Rd, Covington, KY 41011', phone_number: '(859) 491-4003', website: 'https://www.bcmuseum.org/')
activity4 = Activity.create(title: 'Carousel', neighborhood: 'The Banks', cost: 2, address: '8 E Mehring Way, Cincinnati, OH 45202', phone_number: '(513) 381-3756', website: 'https://www.cincinnati-oh.gov/cincyparks/visit-a-park/find-a-parkfacility/carol-anns-carousel/')
activity5 = Activity.create(title: 'Cincinnati Fire Museum', neighborhood: 'Downtown', cost: 8, address: '315 W Court St, Cincinnati, OH 45202', phone_number: '(513) 621-5553', website: 'https://www.cincyfiremuseum.com')

interest1 = Interest.create(name: 'Art exhibits', category: 'Culture')
interest2 = Interest.create(name: 'Concerts', category: 'Culture')
interest3 = Interest.create(name: 'Museums', category: 'Culture')
interest4 = Interest.create(name: 'Musicals', category: 'Culture')
interest5 = Interest.create(name: 'Plays', category: 'Culture')
interest6 = Interest.create(name: 'Tours', category: 'Culture')
interest7 = Interest.create(name: 'Food festivals', category: 'Festivals')
interest8 = Interest.create(name: 'Seasonal events', category: 'Festivals')
interest9 = Interest.create(name: 'Special events', category: 'Festivals')
interest10 = Interest.create(name: 'Biking', category: 'Fitness')
interest11 = Interest.create(name: 'Gym', category: 'Fitness')
interest12 = Interest.create(name: 'Hiking', category: 'Fitness')
interest13 = Interest.create(name: 'Running', category: 'Fitness')
interest14 = Interest.create(name: 'Walking', category: 'Fitness')
interest15 = Interest.create(name: 'Bars', category: 'Going Out')
interest16 = Interest.create(name: 'Restaurants', category: 'Going Out')
interest17 = Interest.create(name: 'Art', category: 'Hobbies')
interest18 = Interest.create(name: 'Baking', category: 'Hobbies')
interest19 = Interest.create(name: 'Cooking', category: 'Hobbies')
interest20 = Interest.create(name: 'Dance', category: 'Hobbies')
interest21 = Interest.create(name: 'Gardening', category: 'Hobbies')
interest22 = Interest.create(name: 'Reading', category: 'Hobbies')
interest23 = Interest.create(name: 'Thrifting', category: 'Hobbies')
interest24 = Interest.create(name: 'Video games', category: 'Hobbies')
interest25 = Interest.create(name: 'Baseball', category: 'Playing Sports')
interest26 = Interest.create(name: 'Basketball', category: 'Playing Sports')
interest27 = Interest.create(name: 'Football', category: 'Playing Sports')
interest28 = Interest.create(name: 'Golf', category: 'Playing Sports')
interest29 = Interest.create(name: 'Pickleball', category: 'Playing Sports')
interest30 = Interest.create(name: 'Skiing', category: 'Playing Sports')
interest31 = Interest.create(name: 'Soccer', category: 'Playing Sports')
interest32 = Interest.create(name: 'Tennis', category: 'Playing Sports')
interest33 = Interest.create(name: 'Ultimate Frisbee', category: 'Playing Sports')
interest34 = Interest.create(name: 'Bengals', category: 'Sporting Events')
interest35 = Interest.create(name: 'Cyclones', category: 'Sporting Events')
interest36 = Interest.create(name: 'FC Cincinnati', category: 'Sporting Events')
interest37 = Interest.create(name: 'Florence Yalls', category: 'Sporting Events')
interest38 = Interest.create(name: 'Reds', category: 'Sporting Events')
interest39 = Interest.create(name: 'Canoeing', category: 'Water Sports')
interest40 = Interest.create(name: 'Kayking', category: 'Water Sports')
interest41 = Interest.create(name: 'SUP', category: 'Water Sports')
interest42 = Interest.create(name: 'Swimming', category: 'Water Sports')

puts "✅ Done seeding!"